import createClient from 'openapi-fetch'
import { apiFetch } from './http'

type ApiRequestInit = Record<string, any>
type ApiResponse<T = any> = Promise<{ data?: T; error?: any; response: Response }>

// HTTP transport stays on openapi-fetch, while API DTOs are generated by Hey API
// from contracts/openapi.json. Keep endpoint DTOs imported from ./hey-api and
// regenerate them with `pnpm gen:api` after backend contract changes.
const rawApi = createClient<any>({ baseUrl: '/', fetch: apiFetch })

export const api = {
  GET: <T = any>(url: string, init?: ApiRequestInit) =>
    rawApi.GET(url as never, (init ?? {}) as never) as ApiResponse<T>,
  POST: <T = any>(url: string, init?: ApiRequestInit) =>
    rawApi.POST(url as never, (init ?? {}) as never) as ApiResponse<T>,
  PUT: <T = any>(url: string, init?: ApiRequestInit) =>
    rawApi.PUT(url as never, (init ?? {}) as never) as ApiResponse<T>,
  PATCH: <T = any>(url: string, init?: ApiRequestInit) =>
    rawApi.PATCH(url as never, (init ?? {}) as never) as ApiResponse<T>,
  DELETE: <T = any>(url: string, init?: ApiRequestInit) =>
    rawApi.DELETE(url as never, (init ?? {}) as never) as ApiResponse<T>,
}
