/**
 * Provider-neutral lifecycle for short-lived generated bytes. Temporary
 * artifacts are disposable and never authoritative records.
 */
@org.springframework.modulith.ApplicationModule(
        type = org.springframework.modulith.ApplicationModule.Type.OPEN)
package com.northstar.core.artifact;
