package com.northstar.core.artifact;

import java.time.Duration;
import java.util.Optional;
import java.util.UUID;

/** Replaceable lifecycle boundary for disposable generated bytes. */
public interface TemporaryArtifactStore {

    Duration retention();

    TemporaryArtifactMetadata put(TemporaryArtifactScope scope, TemporaryArtifactWrite write);

    Optional<TemporaryArtifactMetadata> find(TemporaryArtifactScope scope, UUID artifactId);

    Optional<TemporaryArtifact> peek(TemporaryArtifactScope scope, UUID artifactId);

    Optional<TemporaryArtifact> consume(TemporaryArtifactScope scope, UUID artifactId);

    boolean delete(TemporaryArtifactScope scope, UUID artifactId);

    long deleteSession(String ownerScope, String sessionId);

    TemporaryArtifactStoreStats stats();
}
