package com.northstar.api.assistant;

import org.jspecify.annotations.Nullable;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.ai.chat.client.ChatClient;
import org.springframework.ai.chat.prompt.ChatOptions;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.core.task.AsyncTaskExecutor;
import org.springframework.jdbc.core.simple.JdbcClient;
import org.springframework.stereotype.Service;

/**
 * Gives each conversation a short, human-readable title generated by the LLM,
 * instead of showing the raw first user message in the sidebar. Titles live in
 * their own table ({@code northstar_conversation_title}, V17) so Spring AI's
 * memory schema stays untouched; absence means "not titled yet" and the
 * conversation list falls back to the first user message.
 *
 * <p>Generation is fire-and-forget on a background thread (the chat turn never
 * waits on it) and idempotent: the first call for a conversation writes a row,
 * every later call is a cheap no-op. Any failure is logged and leaves the
 * conversation untitled — the fallback keeps the list working.
 */
@Service
class ConversationTitleService {

    private static final Logger log = LoggerFactory.getLogger(ConversationTitleService.class);

    private static final String PROMPT = """
            Write a title for a chat conversation that opens with the message below. \
            Three to six words, no surrounding quotes, no trailing punctuation, in the \
            language of the message. Reply with the title only.

            Message:
            %s""";

    /** The model only ever sees the opening message; more would waste tokens on titling. */
    private static final int MAX_SOURCE_CHARS = 500;
    /** Matches the title column width (V17); the list further trims for display. */
    private static final int MAX_TITLE_CHARS = 120;

    private final JdbcClient jdbc;
    private final ChatClient chat;
    private final AsyncTaskExecutor executor;
    private final String model;
    private final boolean enabled;

    ConversationTitleService(JdbcClient jdbc, ChatClient chat,
            @Qualifier("applicationTaskExecutor") AsyncTaskExecutor executor,
            @Value("${northstar.assistant.title.model:gpt-5.5}") String model,
            @Value("${northstar.assistant.title.enabled:true}") boolean enabled) {
        this.jdbc = jdbc;
        this.chat = chat;
        this.executor = executor;
        this.model = model;
        this.enabled = enabled;
    }

    /** Schedule titling for this conversation without blocking the caller (the chat turn). */
    void ensureTitleAsync(String conversationId) {
        if (!enabled) {
            return;
        }
        executor.execute(() -> ensureTitle(conversationId));
    }

    /** Title the conversation if it has none yet; a no-op once a title exists. */
    void ensureTitle(String conversationId) {
        try {
            if (hasTitle(conversationId)) {
                return;
            }
            String firstMessage = firstUserMessage(conversationId);
            if (firstMessage == null || firstMessage.isBlank()) {
                return;
            }
            String title = cleanTitle(generate(firstMessage));
            if (title == null) {
                return;
            }
            // ON CONFLICT: two turns can race here; the first write wins, the rest no-op.
            jdbc.sql("""
                    INSERT INTO northstar_conversation_title (conversation_id, title)
                    VALUES (?, ?)
                    ON CONFLICT (conversation_id) DO NOTHING
                    """)
                    .params(conversationId, title)
                    .update();
        } catch (Exception e) {
            // Titling is a nicety — never let it disturb the conversation itself.
            log.warn("Auto-title failed for conversation {} — left untitled", conversationId, e);
        }
    }

    private boolean hasTitle(String conversationId) {
        Long count = jdbc.sql("SELECT COUNT(*) FROM northstar_conversation_title WHERE conversation_id = ?")
                .param(conversationId)
                .query(Long.class)
                .single();
        return count != null && count > 0;
    }

    private @Nullable String firstUserMessage(String conversationId) {
        return jdbc.sql("""
                SELECT content FROM spring_ai_chat_memory
                 WHERE conversation_id = ? AND type = 'USER'
                 ORDER BY sequence_id LIMIT 1
                """)
                .param(conversationId)
                .query(String.class)
                .optional()
                .orElse(null);
    }

    private @Nullable String generate(String firstMessage) {
        String source = firstMessage.length() > MAX_SOURCE_CHARS
                ? firstMessage.substring(0, MAX_SOURCE_CHARS)
                : firstMessage;
        // Override only the model (cheaper tier is fine for titling); gpt-5.5 is a
        // reasoning model that rejects any temperature but 1, so none is set.
        return chat.prompt()
                .options(ChatOptions.builder().model(model))
                .user(PROMPT.formatted(source))
                .call()
                .content();
    }

    /** Strip quotes/whitespace/trailing punctuation and bound the length; null if empty. */
    static @Nullable String cleanTitle(@Nullable String raw) {
        if (raw == null) {
            return null;
        }
        String title = raw.strip().replaceAll("\\s+", " ");
        // Models often wrap a title in quotes despite instructions — peel one layer.
        if (title.length() >= 2
                && (title.startsWith("\"") && title.endsWith("\"")
                        || title.startsWith("'") && title.endsWith("'"))) {
            title = title.substring(1, title.length() - 1).strip();
        }
        title = title.replaceAll("[.,;:!?]+$", "").strip();
        if (title.isBlank()) {
            return null;
        }
        return title.length() <= MAX_TITLE_CHARS
                ? title
                : title.substring(0, MAX_TITLE_CHARS).strip();
    }
}
